server:
  port: 8081

spring:
  application:
    name: payment-service
  threads:
    virtual:
      enabled: true
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_payment_db
    username: postgres
    password: 9909
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump
  endpoint:
    health:
      show-details: always

app:
  internal-secret: ${INTERNAL_SECRET}
  exchange-rate-api-key: ${EXCHANGE_RATE_API_KEY:}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8082}
