server:
  port: 8060

spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthFilter
              args:
                openPaths:
                  - /api/auth/login

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthFilter
              args:
                openPaths:
                  - /api/users/register

        - id: admin-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/admin/**
          filters:
            - AuthFilter

        - id: payment-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/payments/invoices/**
          filters:
            - AuthFilter
jwt:
  secret: ${JWT_SECRET:9a726673ea132d752495738c8230531234567890abcdef1234567890abcdef}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.anudari.gateway_service: DEBUG

security:
  allowlist:
    origins: "127.0.0.1, 0:0:0:0:0:0:0:1"