server:
  port: 8060

spring:
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthFilter
              args:
                openPaths:
                  - /api/auth/login
                  - /api/auth/refresh

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthFilter
              args:
                openPaths:
                  - POST:/api/users

        - id: payment-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/invoices/**
          filters:
            - AuthFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:9a726673ea132d752495738c8230531234567890abcdef1234567890abcdef}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.anudari.gateway_service: DEBUG

security:
  allowlist:
    origins: "127.0.0.1, 0:0:0:0:0:0:0:1"