spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  cloud:
    compatibility-verifier:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/micro_user_db
    username: postgres
    password: 9909
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  flyway:
    enabled: false

server:
  port: 8082

app:
  internal-secret: ${INTERNAL_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump
  endpoint:
    health:
      show-details: always